### ISSUE TITLE
Audio/Video support

### ISSUE THREAD

**Issue by mixflame** [mixflame/livepost#19]
Allow uploading and sending a video, possibly WebM or VP9

**Comment by sp-1234** [comment]
Please record my Down Vote on GIF.
GIF is kill, it's absurdly inefficient (30x bigger file size than VP9 or any modern video codec if compared with similar quality), so there's no point in spending time on anything GIF-related.

**Comment by mixflame** [comment]
Alright, sounds good. We'll kill GIF.

So you suggest WebM and VP9 instead?

**Comment by mixflame** [comment]
Hopefully this will work similar to image posting and not require an upload.

**Comment by mixflame** [comment]
I think we're going with WebM for Videos, MP3 for audio and GIF will still be supported, but not large sizes (of anything).

**Comment by sp-1234** [comment]
MP3 is kill. Better support also Opus for audio (it's not harder to do btw), or everyone will abuse WebM to upload music with dummy video stream (already happens on many imageboards). Because MP3 can't do good sound at low bitrates.

**Comment by mixflame** [comment]
We now support any picture, audio and video format under 5mb. Including GIF, mp4, mp3 and OGG.
