### ISSUE TITLE
posting an oembed link exposes possible mismatched html

### ISSUE THREAD

**Issue by kfatehi** [mixflame/livepost#37]
![image](https://user-images.githubusercontent.com/175305/28865756-c6f96fae-7725-11e7-9d4c-580bf40177de.png)

notice the `">` before `delete` -- this only shows immediately after posting an oembed link (and is no longer there on refresh)

**Comment by mixflame** [comment]
see: https://github.com/mixflame/livepost/issues/31

**Comment by mixflame** [comment]
oembed is now off

**Comment by mixflame** [comment]
still an issue tho

**Comment by mixflame** [comment]
this is gone

**Comment by mixflame** [comment]
we removed oEmbed and reCaptcha, links are now normally just links
